
image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo 'Install pre-requisites' # runs during prebuild
    command: jupyter-lab --ServerApp.token="" --ServerApp.ip="0.0.0.0" --ServerApp.allow_origin="*"

ports:
  - port: 8888
    onOpen: open-browser
  - port: 8050
    onOpen: open-preview