name: fina-4380
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pandas-datareader
  - scipy
  - seaborn
  - statsmodels
  - pip
  - pip:
    - ghp-import
    - jupyter-book
    - jupyterlab
    - jupyterlab-git
    - linearmodels
    - requests-cache
    - yfinance
