name: fina-4380
channels:
  - conda-forge
dependencies:
  - seaborn
  - matplotlib
  - pandas
  - numpy
  - statsmodels
  - scipy
  - jupyterlab
  - jupyter-book
  - jupyterlab-git
  - jupyterlab-lsp
  - linearmodels
  - requests-cache
# prefix: C:\Users\r.herron\Anaconda3\envs\fina-4380
