name: fina-4380
channels:
  - conda-forge
dependencies:
  - ghp-import
  - jupyter-book
  - jupyterlab
  - jupyterlab-git
  - linearmodels
  - matplotlib
  - numpy
  - pandas
  - pandas-datareader
  - requests-cache
  - scipy
  - seaborn
  - statsmodels
  - yfinance
