name: fina-4380
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - statsmodels
  - pip
  - pip:
      - ghp-import
      - jupyter-book
      - jupyterlab
      - jupyterlab-git
      - linearmodels
      - pandas-datareader
      - requests-cache
      - yfinance
